### ISSUE TITLE
Consider a `Module` to be displayed similar to a `Class`, as a "primitive"

### ISSUE THREAD

**Issue by phorsuedzie** [splitwise/super_diff#255] opened 2024-06-24 15:01 UTC
SuperDiff version: 0.12.1 (newest release available)

An inspected `Module` is not displayed with its name, but with its instance variables etc. (by `...::InstanceTreeBuilders::DefaultObject`).

This is different from a `Class`, which is a `SuperDiff.primitive?`, and therefore displayed by `...::InstanceTreeBuilders::Primitive`, with (only) its name.

The ugly output can be seen at an RSpec example description (`rspec --format doc ...`) that is auto-generated from a `be_a` matcher:
```ruby
it { is_expected.to(be_a(TaskJob)) }
```

is shown as
```
is expected to be a kind of #<Module:0x00000001183d33f8 @_dependencies=[], @_included_block=#<Proc:0x000000011941db78>>
```

If (only) either `SuperDiff.primitive?` or `Primitive.applies_to?` is patched to (additionally) return `true` for a `Module === value`, then the output looks better:
```
is expected to be a kind of TaskJob
```

**Comment by jas14** [comment] 2024-09-22 22:29
@phorsuedzie thanks for highlighting this, and for the small reproducible test case!

As you note,  we fall back on the `DefaultObject` inspection tree builder, which shows the class (ironically `Module`) and the object address. It looks like the [object inspection in rspec-support](https://github.com/rspec/rspec-support/blob/a3e3c3dfaae6884f757a843c4cadb946e2985081/lib/rspec/support/object_formatter.rb#L242-L244) just calls `#inspect` on the module, which yields its name.

Confirming what you said, we already have a `Primitive` inspection tree builder, so we'd just need to add `Module` to the primitive list and add some unit and integration tests. I'm marking as a good first issue, PRs welcome!

**Closed as completed** 2024-09-25 21:06 UTC
Labels: 🔧 Improvement, :door: Good First Issue
